import turtle
tom = turtle.Turtle()
tom.shape('turtle')
tom.color('dark brown','orange')
tom.speed(0)

tom.begin_fill()
for count in range (6):
  tom.circle(300,60)
  tom.goto(0,0)
  tom.left(360/100)
tom.end_fill()
tom.color('black')
tom.setheading(0)
tom.begin_fill()
tom.goto(0,-25)
tom.circle(25)
tom.end_fill()
tom.goto(0,0)
tom.rt(90)
tom.pu()
tom.fd(187)
tom.pd()

tom.begin_fill()
tom.fd(300)
tom.left(90)
tom.fd(25)
tom.left(90)
tom.fd(250)
tom.end_fill()
tom.pu()
tom.goto(0,0)
tom.pd()